### ISSUE TITLE
duplicate symbol ​_OBJC_CLASS_​$_PodsDummy_Pods_packager

### ISSUE THREAD

**Issue by xwang-phunware** [CocoaPods/cocoapods-packager#154]
I tried to use the latest `cocoapods-packager` `v1.4.0` to generate `AAA.framework` and `BBB.framework`, and someone import both of those two frameworks got the following error:
````
duplicate symbol ​_OBJC_CLASS_​$_PodsDummy_Pods_packager in:
   /Users/..../AAA.framework/BBB(Pods-packager-dummy.o)
   /Users/..../BBB.framework/AAA(Pods-packager-dummy.o)
duplicate symbol ​_OBJC_METACLASS_​$_PodsDummy_Pods_packager in:
   /Users/..../AAA.framework/BBB(Pods-packager-dummy.o)
   /Users/..../BBB.framework/AAA(Pods-packager-dummy.o)
ld: 2 duplicate symbols for architecture x86_64
````

Then I downgrade the `cocoapods-packager` to `v1.3.0` and I still got the similar issue, the only difference is that the duplicate symbol changes, it's like:
````
duplicate symbol ​_OBJC_CLASS_​$_PodsDummy_Pods in:
   /Users/..../AAA.framework/BBB(Pods-dummy.o)
   /Users/..../BBB.framework/AAA(Pods-dummy.o)
duplicate symbol ​_OBJC_METACLASS_​$_PodsDummy_Pods in:
   /Users/..../AAA.framework/BBB(Pods-dummy.o)
   /Users/..../BBB.framework/AAA(Pods-dummy.o)
ld: 2 duplicate symbols for architecture x86_64
````

Looks like the pods dummy file name is constant instead of project name related. By the way, I tried to work with `cocoapods` `v0.39.0 and v1.0.1`.

**Comment by mdsb100** [comment]
#155

**Comment by yehot** [comment]
same issue +1

**Comment by xwang-phunware** [comment]
Fixed by appending ` --no-mangle --exclude-deps`

**Comment by yehot** [comment]
@xwang-phunware  awesome! thx a lot!

**Comment by EricCheungSCUT** [comment]
@xwang-phunware It works! You save my day !

**Comment by nicolas-miari** [comment]
@peterwangxw

> Fixed by appending ` --no-mangle --exclude-deps`

Sorry for the noob question, but... appending _where_?

**Comment by jaykon** [comment]
> @xwang-phunware It works! You save my day !

how to fixed it?

**Comment by jaykon** [comment]
modify podspec:

s.pod_target_xcconfig = { 'EXCLUDED_SOURCE_FILE_NAMES' => '*-dummy.m'}
s.user_target_xcconfig= { 'EXCLUDED_SOURCE_FILE_NAMES' => '*-dummy.m'}

package again,it works for me.
